language: java
jdk:
  - oraclejdk8

env:
  - SERVER=payara-ci-managed-update,payara-ci-managed,provided
  - SERVER=wildfly,weld-decorator-bundled,bundled
  - SERVER=tomee
  - SERVER=openliberty
script: mvn clean package -P $SERVER

